title: Qiu Lei's Homepage
page-top-title: Qiu Lei
top-section-bg-text: Artificial Intelligence
home-subtitle: Qiu Lei&ensp;|&ensp;仇磊
copyright-text: '&copy; Qiu Lei 2024-2026. All Rights Reserved.'
github-link: joshuaxql
license-link: qiuleiustc@mail.ustc.edu.cn
